name = "Unified Kill Chain"
field = "killchain"
version = "1.0"
description = "Cyber attacks are typically phased progressions towards strategic objectives. The Unified Kill Chains provides insight into the tactics that hackers employ to attain these objectives. This provides a solid basis to develop (or realign) defensive strategies to raise cyber resilience."
reference = "https://www.unifiedkillchain.com/assets/The-Unified-Kill-Chain.pdf"

stages = [ "Initial Foothold", "Network Propagation", "Action on Objectives",]
key = "name"
[[keys]]
name = "Reconnaissance"

description = "Researching, identifying and selecting targets using active or passive reconnaissance."
"tide.vocab.stages" = "Initial Foothold"
misp = "unified-kill-chain:Initial Foothold=\"reconnaissance\""

[[keys]]
name = "Weaponization"

"tide.vocab.stages" = "Initial Foothold"
description = "Preparatory activities aimed at setting up the infrastructure required for the attack."
misp = "unified-kill-chain:Initial Foothold=\"weaponization\""

[[keys]]
name = "Delivery"

"tide.vocab.stages" = "Initial Foothold"
description = "Techniques resulting in the transmission of a weaponized object to the targeted environment."
misp = "unified-kill-chain:Initial Foothold=\"delivery\""

[[keys]]
name = "Social Engineering"

"tide.vocab.stages" = "Initial Foothold"
description = "Techniques aimed at the manipulation of people to perform unsafe actions."
misp = "unified-kill-chain:Initial Foothold=\"social-engineering\""

[[keys]]
name = "Exploitation"

"tide.vocab.stages" = "Initial Foothold"
description = "Techniques to exploit vulnerabilities in systems that may, amongst others, result in code execution."
misp = "unified-kill-chain:Initial Foothold=\"exploitation\""

[[keys]]
name = "Persistence"

"tide.vocab.stages" = "Initial Foothold"
description = "Any access, action or change to a system that gives an attacker persistent presence on the system."
misp = "unified-kill-chain:Initial Foothold=\"persistence\""

[[keys]]
name = "Defense Evasion"

"tide.vocab.stages" = "Initial Foothold"
description = "Techniques an attacker may specifically use for evading detection or avoiding other defenses."
misp = "unified-kill-chain:Initial Foothold=\"defense-evasion\""

[[keys]]
name = "Command & Control"

"tide.vocab.stages" = "Initial Foothold"
description = "Techniques that allow attackers to communicate with controlled systems within a target network."
misp = "unified-kill-chain:Initial Foothold=\"command-control\""

[[keys]]
name = "Pivoting"

"tide.vocab.stages" = "Network Propagation"
description = "Tunneling traffic through a controlled system to other systems that are not directly accessible."
misp = "unified-kill-chain:Network Propagation=\"pivoting\""

[[keys]]
name = "Discovery"

"tide.vocab.stages" = "Network Propagation"
description = "Techniques that allow an attacker to gain knowledge about a system and its network environment."
misp = "unified-kill-chain:Network Propagation=\"discovery\""

[[keys]]
name = "Privilege Escalation"

"tide.vocab.stages" = "Network Propagation"
description = "The result of techniques that provide an attacker with higher permissions on a system or network."
misp = "unified-kill-chain:Network Propagation=\"privilege-escalation\""

[[keys]]
name = "Execution"

"tide.vocab.stages" = "Network Propagation"
description = "Techniques that result in execution of attacker-controlled code on a local or remote system."
misp = "unified-kill-chain:Network Propagation=\"execution\""

[[keys]]
name = "Credential Access"

"tide.vocab.stages" = "Network Propagation"
description = "Techniques resulting in the access of, or control over, system, service or domain credentials."
misp = "unified-kill-chain:Network Propagation=\"credential-access\""

[[keys]]
name = "Lateral Movement"

"tide.vocab.stages" = "Network Propagation"
description = "Techniques that enable an adversary to horizontally access and control other remote systems."
misp = "unified-kill-chain:Network Propagation=\"lateral-movement\""

[[keys]]
name = "Collection"

"tide.vocab.stages" = "Action on Objectives"
description = "Techniques used to identify and gather data from a target network prior to exfiltration."
misp = "unified-kill-chain:Action on Objectives=\"collection\""

[[keys]]
name = "Exfiltration"

"tide.vocab.stages" = "Action on Objectives"
description = "Techniques that result or aid in an attacker removing data from a target network."
misp = "unified-kill-chain:Action on Objectives=\"exfiltration\""

[[keys]]
name = "Impact"

"tide.vocab.stages" = "Action on Objectives"
description = "Techniques aimed at manipulating, interrupting or destroying the target system or data."
misp = "unified-kill-chain:Action on Objectives=\"impact\""

[[keys]]
name = "Objectives"

"tide.vocab.stages" = "Action on Objectives"
description = "Socio-technical objectives of an attack that are intended to achieve a strategic goal."
misp = "unified-kill-chain:Action on Objectives=\"objectives\""
