name = "Strategic Objectives"
field = "objectives"
stix = "attack-motivation-ov"
description = "Purpose of presence in cyberspace by the adversary, and the end goal of the exploitation of targets."
reference = "https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_dmb1khqsn650"

key = "name"
[[keys]]
name = "Disruption"

description = "Temporary or permanent loss of service components, with impact on operations relying on its continuity."

[[keys]]
name = "Defacement"

description = "Alteration of publicly visible organizational asset, for ideological reasons or to damage the reputation of the organization."

[[keys]]
name = "Psychological Operations"

description = "Military and intelligence techniques to convey selected information and indicators to audiences to influence their emotions, motives, and objective reasoning, and ultimately the behavior of governments, organizations, groups, and individuals."

[[keys]]
name = "Confidential Information Theft"

description = "Attacks aim at acquiring undisclosed, private and valuable data from the target."

[[keys]]
name = "Identity Theft/Impersonation"

description = "The adversary aims at stealing identities, typically to allow further malicious operations or for resale on black markets."

[[keys]]
name = "Financial Gain"

stix = "personal-gain"
description = "The desire to improve one’s own financial status.\n\nAdversaries motivated by a selfish desire for personal gain are often out for gains that come from financial fraud, hacking for hire, or intellectual property theft.\n\nWhile a Threat Actor or Intrusion Set may be seeking personal gain, this does not mean they are acting alone. Individuals can band together solely to maximize their own personal profits."

[[keys]]
id = "SGO007"
name = "Organizational Gain"

stix = "organizational-gain"
description = "Seeking advantage over a competing organization, including a military organization.\n\nAdversaries motivated by increased profit or other gains through an unfairly obtained competitive advantage are often seeking theft of intellectual property, business processes, or supply chain agreements and thus accelerating their position in a market or capability."

[[keys]]
name = "Sabotage"

description = "Deliberate and malicious disruption of services with the goal to deny processes, and inflict material or tangible damage."

[[keys]]
name = "Incapacitation"

description = "Full disablement of key functions of an organization, typically for the purpose of national interest, political belief or terrorism."

[[keys]]
name = "Espionage"

description = "Intelligence techniques applied to cyberspace, where the adversaries will work toward nation-state goals through continuous observation and monitoring of confidential information."

[[keys]]
name = "Ideology"

stix = "ideology"
description = "Adversaries who act for ideological reasons (e.g., political, religious, human rights, environmental, desire to cause chaos/anarchy, etc.) are not usually motivated primarily by the desire for profit; they are acting on their own sense of morality, justice, or political loyalty."

[[keys]]
name = "Unpredictable"

stix = "unpredictable"
description = "Unpredictable is not a miscellaneous or default category. Unpredictable means a truly random and likely bizarre event, which seems to have no logical purpose to the victims."

[[keys]]
name = "Coercion"

stix = "coercion"
description = "Being forced to act on someone else's behalf.\n\nAdversaries who are motivated by coercion are often forced through intimidation or blackmail to act illegally for someone else’s benefit. Unlike the other motivations, a coerced person does not act for personal gain, but out of fear of incurring a loss."

[[keys]]
name = "Dominance"

stix = "dominance"
description = "A desire to assert superiority over someone or something else.\n\nAdversaries who are seeking dominance over a target are focused on using their power to force their target into submission or irrelevance. Dominance may be found with ideology in some state-sponsored attacks and with notoriety in some cyber vandalism-based attacks."
