name = "Traffic Light Protocol"
field = "tlp"
description = "The Traffic Light Protocol - or short: TLP - was designed with the objective to create a favorable classification scheme for sharing sensitive information while keeping the control over its distribution at the same time."
reference = "https://www.first.org/tlp/"

key = "name"
[[keys]]
id = "TLP:CLEAR"
name = "clear"

misp = "tlp:clear"
description = "Recipients can spread this to the world, there is no limit on disclosure."

[[keys]]
id = "TLP:GREEN"
name = "green"
misp = "tlp:green"

description = "Limited disclosure, recipients can spread this within their community. Sources may use TLP:GREEN when information is useful to increase awareness within their wider community."

[[keys]]
id = "TLP:AMBER"
name = "amber"

misp = "tlp:amber"
description = "Limited disclosure, recipients can only spread this on a need-to-know basis within their organization and its clients."

[[keys]]
id = "TLP:AMBER+STRICT"
name = "amber+strict"

misp = "tlp:amber+strict"
description = "Similar to TLP:AMBER, but restricts sharing to the organization only."

[[keys]]
id = "TLP:RED"
name = "red"

misp = "tlp:red"
description = "For the eyes and ears of individual recipients only, no further disclosure."
